# Generated by Django 5.0.4 on 2024-05-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('keyword', models.TextField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('content', models.TextField(default='')),
                ('published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
