# Generated by Django 5.0.4 on 2024-05-04 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='article',
            name='user_id',
            field=models.TextField(max_length=255),
        ),
    ]
